const mathConceptRoadmap = {
  version: "1.0.0",
  purpose: [
    "학습 로드맵",
    "레벨테스트",
    "AI 약점진단",
    "맞춤형 복습 추천",
    "다음 학습 경로 추천",
  ],
  domains: [
    {
      id: "number_operation",
      name: "수와 연산",
      roadmap: [
        "number_sense",
        "addition_basic",
        "subtraction_basic",
        "multiplication_basic",
        "division_basic",
        "mixed_calculation",
        "factor_multiple",
        "fraction_basic",
        "decimal_basic",
        "ratio_basic",
        "proportion",
        "integer_rational",
        "algebraic_expression",
        "linear_equation",
        "simultaneous_equation",
        "quadratic_equation",
        "function_basic",
        "exponential_logarithmic",
        "calculus_basic",
      ],
    },
    {
      id: "geometry",
      name: "도형",
      roadmap: [
        "shape_basic",
        "triangle_basic",
        "quadrilateral_basic",
        "polygon_area",
        "circle_basic",
        "angle_basic",
        "congruence_symmetry",
        "similarity",
        "pythagorean",
        "trigonometric_ratio",
        "coordinate_plane",
        "analytic_geometry",
        "vector_basic",
        "solid_geometry",
      ],
    },
    {
      id: "data_probability",
      name: "자료·확률·통계",
      roadmap: [
        "classification",
        "table_graph_basic",
        "bar_line_graph",
        "average_basic",
        "data_interpretation",
        "counting_cases",
        "probability_basic",
        "statistics_basic",
        "probability_distribution",
      ],
    },
  ],
  gradeUnits: {
    "초1": ["9까지의 수", "여러 가지 모양", "덧셈과 뺄셈", "비교하기", "50까지의 수", "시계 보기", "규칙 찾기"],
    "초2": ["세 자리 수", "여러 가지 도형", "덧셈과 뺄셈", "길이 재기", "분류하기", "곱셈구구", "시각과 시간"],
    "초3": ["덧셈과 뺄셈", "평면도형", "나눗셈", "곱셈", "길이와 시간", "분수와 소수", "자료의 정리"],
    "초4": ["큰 수", "각도", "곱셈과 나눗셈", "평면도형의 이동", "막대그래프", "분수의 덧셈과 뺄셈", "소수의 덧셈과 뺄셈"],
    "초5": ["자연수의 혼합 계산", "약수와 배수", "규칙과 대응", "약분과 통분", "분수의 덧셈과 뺄셈", "다각형의 둘레와 넓이", "수의 범위와 어림하기", "분수의 곱셈", "합동과 대칭", "평균과 가능성"],
    "초6": ["분수의 나눗셈", "각기둥과 각뿔", "소수의 나눗셈", "비와 비율", "여러 가지 그래프", "직육면체의 부피와 겉넓이", "비례식과 비례배분", "원의 넓이", "원기둥·원뿔·구", "경우의 수"],
    "중1": ["소인수분해", "정수와 유리수", "문자와 식", "일차방정식", "좌표평면", "정비례와 반비례", "기본도형", "작도와 합동", "자료의 정리와 해석"],
    "중2": ["유리수와 순환소수", "식의 계산", "연립일차방정식", "일차함수", "삼각형의 성질", "사각형의 성질", "닮음의 기초", "경우의 수", "확률"],
    "중3": ["실수", "다항식의 인수분해", "이차방정식", "이차함수", "피타고라스 정리", "원의 성질", "삼각비", "대푯값과 산포도"],
    "공통수학": ["다항식", "방정식과 부등식", "경우의 수", "행렬", "도형의 방정식", "집합과 명제", "함수", "지수함수와 로그함수"],
    "수학Ⅰ": ["지수함수", "로그함수", "삼각함수", "수열"],
    "수학Ⅱ": ["함수의 극한", "미분", "적분"],
    "미적분": ["수열의 극한", "미분법", "적분법"],
    "확률과 통계": ["경우의 수", "확률", "통계"],
    "기하": ["이차곡선", "평면벡터", "공간도형과 공간좌표"],
  },
  concepts: [
    {
      id: "number_sense",
      conceptName: "수 개념",
      schoolLevel: "초등",
      grade: "초1",
      domain: "수와 연산",
      description: "수의 크기, 순서, 묶음, 자리값의 기초를 이해하는 단계",
      prerequisites: [],
      nextConcepts: ["addition_basic", "subtraction_basic", "place_value"],
      difficultyLevel: 1,
      relatedUnits: ["9까지의 수", "50까지의 수", "세 자리 수"],
      levelTestQuestionCount: 4,
      testQuestionTypes: ["수 읽기", "수 비교", "수 가르기", "순서 찾기"],
      minimumPassScore: 80,
      masteryCriteria: { accuracy: 0.85, maxAverageSeconds: 5, requiredConsecutiveCorrect: 3 },
      commonMistakes: ["수의 순서 혼동", "자리값 미이해", "크기 비교 오류"],
      diagnosisRules: [
        { if: "두 자리 수 비교 오답", then: ["number_sense", "place_value"] },
        { if: "수 가르기 지연", then: ["number_sense"] },
      ],
      recommendedReviewConcepts: [],
      levelTestDifficulty: [1, 1, 2, 2, 3],
    },
    {
      id: "addition_basic",
      conceptName: "덧셈",
      schoolLevel: "초등",
      grade: "초1",
      domain: "수와 연산",
      description: "두 수를 합하여 전체 수량을 구하는 개념",
      prerequisites: ["number_sense"],
      nextConcepts: ["subtraction_basic", "carry_addition", "multiplication_basic"],
      difficultyLevel: 1,
      relatedUnits: ["덧셈과 뺄셈"],
      levelTestQuestionCount: 5,
      testQuestionTypes: ["한 자리 덧셈", "두 자리 덧셈", "받아올림"],
      minimumPassScore: 85,
      masteryCriteria: { accuracy: 0.9, maxAverageSeconds: 5, requiredConsecutiveCorrect: 4 },
      commonMistakes: ["받아올림 누락", "자리 맞춤 오류", "수 가르기 부족"],
      diagnosisRules: [
        { if: "받아올림 덧셈 오답", then: ["number_sense", "place_value"] },
        { if: "계산 속도 지연", then: ["addition_basic"] },
      ],
      recommendedReviewConcepts: ["number_sense", "place_value"],
      levelTestDifficulty: [1, 2, 2, 3, 3],
    },
    {
      id: "subtraction_basic",
      conceptName: "뺄셈",
      schoolLevel: "초등",
      grade: "초1",
      domain: "수와 연산",
      description: "전체에서 일부를 덜어 남은 양이나 차이를 구하는 개념",
      prerequisites: ["number_sense", "addition_basic"],
      nextConcepts: ["borrow_subtraction", "division_basic"],
      difficultyLevel: 2,
      relatedUnits: ["덧셈과 뺄셈"],
      levelTestQuestionCount: 5,
      testQuestionTypes: ["한 자리 뺄셈", "두 자리 뺄셈", "받아내림"],
      minimumPassScore: 80,
      masteryCriteria: { accuracy: 0.85, maxAverageSeconds: 6, requiredConsecutiveCorrect: 4 },
      commonMistakes: ["받아내림 오류", "큰 수에서 작은 수 빼기 순서 혼동", "덧셈과 뺄셈 관계 미이해"],
      diagnosisRules: [
        { if: "받아내림 뺄셈 오답", then: ["addition_basic", "place_value"] },
      ],
      recommendedReviewConcepts: ["addition_basic", "place_value"],
      levelTestDifficulty: [1, 2, 3, 3, 4],
    },
    {
      id: "place_value",
      conceptName: "자리값",
      schoolLevel: "초등",
      grade: "초2",
      domain: "수와 연산",
      description: "일의 자리, 십의 자리, 백의 자리 등 수 위치가 나타내는 값을 이해하는 개념",
      prerequisites: ["number_sense"],
      nextConcepts: ["carry_addition", "borrow_subtraction", "large_numbers"],
      difficultyLevel: 2,
      relatedUnits: ["세 자리 수", "큰 수"],
      levelTestQuestionCount: 4,
      testQuestionTypes: ["자리값 읽기", "수 전개", "크기 비교"],
      minimumPassScore: 80,
      masteryCriteria: { accuracy: 0.85, maxAverageSeconds: 7, requiredConsecutiveCorrect: 3 },
      commonMistakes: ["0이 포함된 수 읽기 오류", "자리 바꾸기 오류", "수 전개 오류"],
      diagnosisRules: [
        { if: "세 자리 수 계산 오류", then: ["place_value", "addition_basic"] },
      ],
      recommendedReviewConcepts: ["number_sense"],
      levelTestDifficulty: [2, 2, 3, 3],
    },
    {
      id: "multiplication_basic",
      conceptName: "곱셈",
      schoolLevel: "초등",
      grade: "초2",
      domain: "수와 연산",
      description: "같은 수를 여러 번 더하는 상황을 간단히 나타내는 연산",
      prerequisites: ["addition_basic", "number_sense"],
      nextConcepts: ["division_basic", "multi_digit_multiplication", "area_basic"],
      difficultyLevel: 2,
      relatedUnits: ["곱셈구구", "곱셈"],
      levelTestQuestionCount: 6,
      testQuestionTypes: ["곱셈구구", "배열", "두 자리수 곱셈 기초"],
      minimumPassScore: 85,
      masteryCriteria: { accuracy: 0.9, maxAverageSeconds: 6, requiredConsecutiveCorrect: 5 },
      commonMistakes: ["구구단 암기 부족", "반복덧셈 의미 미이해", "자리 올림 오류"],
      diagnosisRules: [
        { if: "곱셈구구 지연", then: ["addition_basic", "multiplication_basic"] },
      ],
      recommendedReviewConcepts: ["addition_basic"],
      levelTestDifficulty: [1, 2, 2, 3, 3],
    },
    {
      id: "division_basic",
      conceptName: "나눗셈",
      schoolLevel: "초등",
      grade: "초3",
      domain: "수와 연산",
      description: "전체를 같은 크기로 나누거나 한 묶음의 수를 구하는 연산",
      prerequisites: ["multiplication_basic", "subtraction_basic"],
      nextConcepts: ["fraction_basic", "ratio_basic", "decimal_division"],
      difficultyLevel: 3,
      relatedUnits: ["나눗셈", "나머지 있는 나눗셈"],
      levelTestQuestionCount: 6,
      testQuestionTypes: ["나눗셈식", "나머지", "곱셈과 나눗셈 관계"],
      minimumPassScore: 80,
      masteryCriteria: { accuracy: 0.85, maxAverageSeconds: 10, requiredConsecutiveCorrect: 4 },
      commonMistakes: ["몫과 나머지 혼동", "나누는 수/나누어지는 수 혼동", "곱셈 역연산 미이해"],
      diagnosisRules: [
        { if: "나눗셈 오답", then: ["multiplication_basic", "subtraction_basic"] },
      ],
      recommendedReviewConcepts: ["multiplication_basic"],
      levelTestDifficulty: [2, 3, 3, 4],
    },
    {
      id: "fraction_basic",
      conceptName: "분수의 기초",
      schoolLevel: "초등",
      grade: "초3",
      domain: "수와 연산",
      description: "전체를 똑같이 나눈 부분을 수로 나타내는 개념",
      prerequisites: ["number_sense", "division_basic", "equal_parts"],
      nextConcepts: ["fraction_addition", "fraction_subtraction", "fraction_multiplication", "ratio_basic"],
      difficultyLevel: 3,
      relatedUnits: ["분수", "분수와 소수"],
      levelTestQuestionCount: 6,
      testQuestionTypes: ["분수 읽기", "크기 비교", "동치분수", "수직선"],
      minimumPassScore: 80,
      masteryCriteria: { accuracy: 0.85, maxAverageSeconds: 15, requiredConsecutiveCorrect: 4 },
      commonMistakes: ["분모/분자 역할 혼동", "전체 기준 미확인", "분수 크기 비교 오류"],
      diagnosisRules: [
        { if: "분수 크기 비교 오답", then: ["division_basic", "equal_parts"] },
      ],
      recommendedReviewConcepts: ["division_basic", "equal_parts"],
      levelTestDifficulty: [2, 3, 3, 4],
    },
    {
      id: "fraction_operations",
      conceptName: "분수 계산",
      schoolLevel: "초등",
      grade: "초4~6",
      domain: "수와 연산",
      description: "통분, 약분을 바탕으로 분수의 덧셈, 뺄셈, 곱셈, 나눗셈을 수행하는 개념",
      prerequisites: ["fraction_basic", "factor_multiple", "division_basic"],
      nextConcepts: ["ratio_basic", "proportion", "rational_number_operation"],
      difficultyLevel: 4,
      relatedUnits: ["약분과 통분", "분수의 덧셈과 뺄셈", "분수의 곱셈", "분수의 나눗셈"],
      levelTestQuestionCount: 8,
      testQuestionTypes: ["통분", "약분", "이분모 분수 덧셈", "분수 곱셈", "분수 나눗셈"],
      minimumPassScore: 78,
      masteryCriteria: { accuracy: 0.82, maxAverageSeconds: 25, requiredConsecutiveCorrect: 5 },
      commonMistakes: ["분모끼리 더함", "통분 누락", "나눗셈에서 역수 변환 누락", "약분 실수"],
      diagnosisRules: [
        { if: "통분 오답", then: ["factor_multiple", "fraction_basic"] },
        { if: "분수 나눗셈 오답", then: ["fraction_multiplication", "division_basic"] },
      ],
      recommendedReviewConcepts: ["fraction_basic", "factor_multiple"],
      levelTestDifficulty: [3, 3, 4, 4, 5],
    },
    {
      id: "decimal_basic",
      conceptName: "소수",
      schoolLevel: "초등",
      grade: "초3~6",
      domain: "수와 연산",
      description: "분모가 10, 100, 1000인 분수를 십진법으로 표현하는 개념",
      prerequisites: ["place_value", "fraction_basic"],
      nextConcepts: ["decimal_operations", "ratio_basic", "rational_number_operation"],
      difficultyLevel: 3,
      relatedUnits: ["분수와 소수", "소수의 덧셈과 뺄셈", "소수의 나눗셈"],
      levelTestQuestionCount: 6,
      testQuestionTypes: ["소수 읽기", "분수-소수 변환", "소수 계산"],
      minimumPassScore: 80,
      masteryCriteria: { accuracy: 0.85, maxAverageSeconds: 20, requiredConsecutiveCorrect: 4 },
      commonMistakes: ["소수점 자리 오류", "0 처리 오류", "분수와 소수 변환 오류"],
      diagnosisRules: [
        { if: "소수 자리 오류", then: ["place_value"] },
      ],
      recommendedReviewConcepts: ["place_value", "fraction_basic"],
      levelTestDifficulty: [2, 3, 3, 4],
    },
    {
      id: "ratio_basic",
      conceptName: "비와 비율",
      schoolLevel: "초등",
      grade: "초6",
      domain: "수와 연산",
      description: "두 양의 관계를 나눗셈과 분수로 표현하는 개념",
      prerequisites: ["division_basic", "fraction_operations", "decimal_basic"],
      nextConcepts: ["proportion", "linear_function", "trigonometric_ratio", "probability_basic"],
      difficultyLevel: 4,
      relatedUnits: ["비와 비율", "백분율"],
      levelTestQuestionCount: 7,
      testQuestionTypes: ["비 읽기", "비율 계산", "백분율", "문장제"],
      minimumPassScore: 78,
      masteryCriteria: { accuracy: 0.82, maxAverageSeconds: 30, requiredConsecutiveCorrect: 4 },
      commonMistakes: ["기준량/비교하는 양 혼동", "분수 변환 오류", "백분율 변환 오류"],
      diagnosisRules: [
        { if: "비율 오답", then: ["fraction_operations", "division_basic"] },
      ],
      recommendedReviewConcepts: ["fraction_operations", "division_basic"],
      levelTestDifficulty: [3, 4, 4, 5],
    },
    {
      id: "proportion",
      conceptName: "비례식과 비례배분",
      schoolLevel: "초등",
      grade: "초6",
      domain: "수와 연산",
      description: "두 비가 같음을 이용해 미지의 양을 구하고 전체를 비에 따라 나누는 개념",
      prerequisites: ["ratio_basic", "fraction_operations", "division_basic"],
      nextConcepts: ["linear_function", "similarity", "trigonometric_ratio"],
      difficultyLevel: 4,
      relatedUnits: ["비례식과 비례배분", "정비례와 반비례"],
      levelTestQuestionCount: 7,
      testQuestionTypes: ["비례식", "비례배분", "문장제"],
      minimumPassScore: 78,
      masteryCriteria: { accuracy: 0.82, maxAverageSeconds: 35, requiredConsecutiveCorrect: 4 },
      commonMistakes: ["내항/외항 곱 오류", "전체량 배분 오류", "비율 기준 혼동"],
      diagnosisRules: [
        { if: "비례식 오답", then: ["ratio_basic", "fraction_operations", "division_basic"] },
      ],
      recommendedReviewConcepts: ["ratio_basic", "fraction_operations"],
      levelTestDifficulty: [3, 4, 4, 5],
    },
    {
      id: "integer_rational",
      conceptName: "정수와 유리수",
      schoolLevel: "중등",
      grade: "중1",
      domain: "수와 연산",
      description: "음수, 정수, 유리수의 크기와 사칙연산을 이해하는 개념",
      prerequisites: ["fraction_operations", "decimal_basic", "number_sense"],
      nextConcepts: ["algebraic_expression", "linear_equation", "rational_number_operation"],
      difficultyLevel: 5,
      relatedUnits: ["정수와 유리수", "유리수와 순환소수"],
      levelTestQuestionCount: 8,
      testQuestionTypes: ["부호 계산", "절댓값", "유리수 사칙연산"],
      minimumPassScore: 80,
      masteryCriteria: { accuracy: 0.85, maxAverageSeconds: 35, requiredConsecutiveCorrect: 5 },
      commonMistakes: ["음수 부호 오류", "절댓값 혼동", "분수 계산 오류"],
      diagnosisRules: [
        { if: "유리수 계산 오답", then: ["fraction_operations", "decimal_basic"] },
      ],
      recommendedReviewConcepts: ["fraction_operations", "decimal_basic"],
      levelTestDifficulty: [3, 4, 4, 5],
    },
    {
      id: "algebraic_expression",
      conceptName: "문자식",
      schoolLevel: "중등",
      grade: "중1",
      domain: "문자와 식",
      description: "수를 문자로 일반화하고 식으로 표현·계산하는 개념",
      prerequisites: ["integer_rational", "multiplication_basic", "division_basic"],
      nextConcepts: ["linear_equation", "polynomial_operation"],
      difficultyLevel: 5,
      relatedUnits: ["문자와 식", "식의 계산"],
      levelTestQuestionCount: 8,
      testQuestionTypes: ["문자식 표현", "동류항 정리", "대입"],
      minimumPassScore: 78,
      masteryCriteria: { accuracy: 0.82, maxAverageSeconds: 40, requiredConsecutiveCorrect: 5 },
      commonMistakes: ["문자와 수의 곱 표기 혼동", "동류항 미구분", "대입 계산 오류"],
      diagnosisRules: [
        { if: "문자식 계산 오답", then: ["integer_rational", "multiplication_basic"] },
      ],
      recommendedReviewConcepts: ["integer_rational"],
      levelTestDifficulty: [3, 4, 4, 5],
    },
    {
      id: "linear_equation",
      conceptName: "일차방정식",
      schoolLevel: "중등",
      grade: "중1",
      domain: "문자와 식",
      description: "미지수가 1차인 등식을 풀어 미지수의 값을 구하는 개념",
      prerequisites: ["algebraic_expression", "integer_rational", "equation_property"],
      nextConcepts: ["simultaneous_equation", "linear_function", "inequality_linear"],
      difficultyLevel: 5,
      relatedUnits: ["일차방정식"],
      levelTestQuestionCount: 8,
      testQuestionTypes: ["기본 풀이", "괄호", "분수계수", "활용문제"],
      minimumPassScore: 78,
      masteryCriteria: { accuracy: 0.82, maxAverageSeconds: 45, requiredConsecutiveCorrect: 5 },
      commonMistakes: ["이항 부호 오류", "등식의 성질 미이해", "분배법칙 오류"],
      diagnosisRules: [
        { if: "일차방정식 오답", then: ["algebraic_expression", "integer_rational", "equation_property"] },
      ],
      recommendedReviewConcepts: ["algebraic_expression", "integer_rational"],
      levelTestDifficulty: [3, 4, 4, 5],
    },
    {
      id: "coordinate_plane",
      conceptName: "좌표평면",
      schoolLevel: "중등",
      grade: "중1",
      domain: "함수",
      description: "순서쌍으로 평면 위 위치를 나타내는 개념",
      prerequisites: ["number_sense", "integer_rational"],
      nextConcepts: ["linear_function", "quadratic_function", "analytic_geometry"],
      difficultyLevel: 4,
      relatedUnits: ["좌표평면", "일차함수", "도형의 방정식"],
      levelTestQuestionCount: 6,
      testQuestionTypes: ["좌표 읽기", "사분면", "그래프 해석"],
      minimumPassScore: 80,
      masteryCriteria: { accuracy: 0.85, maxAverageSeconds: 30, requiredConsecutiveCorrect: 4 },
      commonMistakes: ["x,y좌표 순서 혼동", "음수 좌표 위치 오류", "사분면 혼동"],
      diagnosisRules: [
        { if: "좌표평면 오답", then: ["integer_rational", "number_sense"] },
      ],
      recommendedReviewConcepts: ["integer_rational"],
      levelTestDifficulty: [2, 3, 3, 4],
    },
    {
      id: "simultaneous_equation",
      conceptName: "연립일차방정식",
      schoolLevel: "중등",
      grade: "중2",
      domain: "문자와 식",
      description: "두 개 이상의 일차방정식을 동시에 만족하는 해를 구하는 개념",
      prerequisites: ["linear_equation", "algebraic_expression", "integer_rational"],
      nextConcepts: ["linear_function", "quadratic_equation"],
      difficultyLevel: 6,
      relatedUnits: ["연립일차방정식"],
      levelTestQuestionCount: 8,
      testQuestionTypes: ["대입법", "가감법", "활용문제", "그래프 해석"],
      minimumPassScore: 76,
      masteryCriteria: { accuracy: 0.8, maxAverageSeconds: 55, requiredConsecutiveCorrect: 5 },
      commonMistakes: ["가감 부호 오류", "대입식 정리 오류", "해 검산 누락"],
      diagnosisRules: [
        { if: "연립방정식 오답", then: ["linear_equation", "algebraic_expression", "integer_rational"] },
      ],
      recommendedReviewConcepts: ["linear_equation", "algebraic_expression"],
      levelTestDifficulty: [3, 4, 4, 5],
    },
    {
      id: "linear_function",
      conceptName: "일차함수",
      schoolLevel: "중등",
      grade: "중2",
      domain: "함수",
      description: "변화율이 일정한 두 변수의 관계를 식과 그래프로 나타내는 개념",
      prerequisites: ["coordinate_plane", "linear_equation", "proportion"],
      nextConcepts: ["quadratic_function", "function_basic", "analytic_geometry"],
      difficultyLevel: 6,
      relatedUnits: ["정비례와 반비례", "일차함수"],
      levelTestQuestionCount: 8,
      testQuestionTypes: ["기울기", "절편", "그래프", "교점", "활용"],
      minimumPassScore: 76,
      masteryCriteria: { accuracy: 0.8, maxAverageSeconds: 55, requiredConsecutiveCorrect: 5 },
      commonMistakes: ["기울기/절편 혼동", "좌표 대입 오류", "그래프 해석 오류"],
      diagnosisRules: [
        { if: "일차함수 오답", then: ["coordinate_plane", "linear_equation", "proportion"] },
      ],
      recommendedReviewConcepts: ["coordinate_plane", "linear_equation", "proportion"],
      levelTestDifficulty: [3, 4, 4, 5],
    },
    {
      id: "similarity",
      conceptName: "닮음",
      schoolLevel: "중등",
      grade: "중2",
      domain: "도형",
      description: "모양이 같고 크기만 다른 도형 사이의 대응 관계를 이해하는 개념",
      prerequisites: ["ratio_basic", "triangle_basic", "proportion"],
      nextConcepts: ["pythagorean", "trigonometric_ratio", "analytic_geometry"],
      difficultyLevel: 6,
      relatedUnits: ["닮음의 기초", "삼각형의 성질"],
      levelTestQuestionCount: 7,
      testQuestionTypes: ["닮음비", "넓이비", "대응변", "증명"],
      minimumPassScore: 76,
      masteryCriteria: { accuracy: 0.8, maxAverageSeconds: 55, requiredConsecutiveCorrect: 4 },
      commonMistakes: ["대응변 매칭 오류", "닮음비와 넓이비 혼동", "비례식 오류"],
      diagnosisRules: [
        { if: "닮음 오답", then: ["ratio_basic", "proportion", "triangle_basic"] },
      ],
      recommendedReviewConcepts: ["ratio_basic", "proportion"],
      levelTestDifficulty: [3, 4, 4, 5],
    },
    {
      id: "pythagorean",
      conceptName: "피타고라스 정리",
      schoolLevel: "중등",
      grade: "중3",
      domain: "도형",
      description: "직각삼각형에서 세 변의 길이 관계를 이용하는 정리",
      prerequisites: ["triangle_basic", "square_root", "similarity"],
      nextConcepts: ["trigonometric_ratio", "analytic_geometry", "vector_basic"],
      difficultyLevel: 6,
      relatedUnits: ["피타고라스 정리"],
      levelTestQuestionCount: 7,
      testQuestionTypes: ["빗변 구하기", "한 변 구하기", "좌표 거리", "활용"],
      minimumPassScore: 76,
      masteryCriteria: { accuracy: 0.8, maxAverageSeconds: 55, requiredConsecutiveCorrect: 4 },
      commonMistakes: ["빗변 구분 오류", "제곱/제곱근 계산 오류", "직각 조건 미확인"],
      diagnosisRules: [
        { if: "피타고라스 오답", then: ["triangle_basic", "square_root", "similarity"] },
      ],
      recommendedReviewConcepts: ["square_root", "similarity"],
      levelTestDifficulty: [3, 4, 4, 5],
    },
    {
      id: "polynomial_operation",
      conceptName: "다항식 계산",
      schoolLevel: "중등",
      grade: "중3",
      domain: "문자와 식",
      description: "다항식의 덧셈, 뺄셈, 곱셈과 전개를 수행하는 개념",
      prerequisites: ["algebraic_expression", "integer_rational", "distributive_property"],
      nextConcepts: ["factorization", "quadratic_equation", "polynomial_high"],
      difficultyLevel: 6,
      relatedUnits: ["다항식의 인수분해", "다항식"],
      levelTestQuestionCount: 8,
      testQuestionTypes: ["전개", "동류항", "곱셈 공식", "식 변형"],
      minimumPassScore: 76,
      masteryCriteria: { accuracy: 0.8, maxAverageSeconds: 55, requiredConsecutiveCorrect: 5 },
      commonMistakes: ["분배법칙 누락", "부호 오류", "지수법칙 오류"],
      diagnosisRules: [
        { if: "다항식 전개 오답", then: ["algebraic_expression", "integer_rational"] },
      ],
      recommendedReviewConcepts: ["algebraic_expression", "integer_rational"],
      levelTestDifficulty: [3, 4, 4, 5],
    },
    {
      id: "factorization",
      conceptName: "인수분해",
      schoolLevel: "중등",
      grade: "중3",
      domain: "문자와 식",
      description: "다항식을 여러 인수의 곱으로 나타내는 개념",
      prerequisites: ["polynomial_operation", "multiplication_basic", "algebraic_expression"],
      nextConcepts: ["quadratic_equation", "rational_expression"],
      difficultyLevel: 7,
      relatedUnits: ["다항식의 인수분해"],
      levelTestQuestionCount: 8,
      testQuestionTypes: ["공통인수", "곱셈공식 역이용", "이차식 인수분해"],
      minimumPassScore: 75,
      masteryCriteria: { accuracy: 0.78, maxAverageSeconds: 60, requiredConsecutiveCorrect: 5 },
      commonMistakes: ["부호 조합 오류", "공통인수 누락", "전개 검산 누락"],
      diagnosisRules: [
        { if: "인수분해 오답", then: ["polynomial_operation", "algebraic_expression", "integer_rational"] },
      ],
      recommendedReviewConcepts: ["polynomial_operation", "algebraic_expression"],
      levelTestDifficulty: [3, 4, 4, 5],
    },
    {
      id: "quadratic_equation",
      conceptName: "이차방정식",
      schoolLevel: "중등",
      grade: "중3",
      domain: "문자와 식",
      description: "미지수의 최고차항이 2차인 방정식을 푸는 개념",
      prerequisites: ["factorization", "polynomial_operation", "square_root", "linear_equation"],
      nextConcepts: ["quadratic_function", "polynomial_high"],
      difficultyLevel: 7,
      relatedUnits: ["이차방정식"],
      levelTestQuestionCount: 8,
      testQuestionTypes: ["인수분해 풀이", "제곱근 풀이", "근의 공식", "활용"],
      minimumPassScore: 75,
      masteryCriteria: { accuracy: 0.78, maxAverageSeconds: 65, requiredConsecutiveCorrect: 5 },
      commonMistakes: ["인수분해 실패", "근 2개 누락", "부호 오류", "제곱근 처리 오류"],
      diagnosisRules: [
        { if: "이차방정식 오답", then: ["factorization", "polynomial_operation", "algebraic_expression", "integer_rational"] },
      ],
      recommendedReviewConcepts: ["factorization", "polynomial_operation", "linear_equation"],
      levelTestDifficulty: [3, 4, 4, 5],
    },
    {
      id: "quadratic_function",
      conceptName: "이차함수",
      schoolLevel: "중등",
      grade: "중3",
      domain: "함수",
      description: "y=ax²+bx+c 꼴의 함수와 그래프의 성질을 이해하는 개념",
      prerequisites: ["coordinate_plane", "linear_function", "quadratic_equation", "polynomial_operation"],
      nextConcepts: ["function_basic", "calculus_basic"],
      difficultyLevel: 7,
      relatedUnits: ["이차함수"],
      levelTestQuestionCount: 8,
      testQuestionTypes: ["꼭짓점", "축", "그래프 이동", "교점"],
      minimumPassScore: 75,
      masteryCriteria: { accuracy: 0.78, maxAverageSeconds: 70, requiredConsecutiveCorrect: 5 },
      commonMistakes: ["꼭짓점 계산 오류", "그래프 방향 혼동", "좌표 대입 오류"],
      diagnosisRules: [
        { if: "이차함수 오답", then: ["coordinate_plane", "linear_function", "quadratic_equation"] },
      ],
      recommendedReviewConcepts: ["coordinate_plane", "linear_function", "quadratic_equation"],
      levelTestDifficulty: [3, 4, 4, 5],
    },
    {
      id: "trigonometric_ratio",
      conceptName: "삼각비",
      schoolLevel: "중등",
      grade: "중3",
      domain: "도형",
      description: "직각삼각형에서 각과 변의 비율 관계를 나타내는 개념",
      prerequisites: ["ratio_basic", "pythagorean", "triangle_basic"],
      nextConcepts: ["trigonometric_function", "analytic_geometry", "vector_basic"],
      difficultyLevel: 7,
      relatedUnits: ["삼각비", "삼각함수"],
      levelTestQuestionCount: 7,
      testQuestionTypes: ["sin/cos/tan", "특수각", "길이 구하기", "활용"],
      minimumPassScore: 75,
      masteryCriteria: { accuracy: 0.78, maxAverageSeconds: 65, requiredConsecutiveCorrect: 4 },
      commonMistakes: ["분자/분모 변 위치 혼동", "각 기준 혼동", "피타고라스 선행 부족"],
      diagnosisRules: [
        { if: "삼각비 오답", then: ["ratio_basic", "pythagorean", "triangle_basic"] },
      ],
      recommendedReviewConcepts: ["ratio_basic", "pythagorean"],
      levelTestDifficulty: [3, 4, 4, 5],
    },
    {
      id: "function_basic",
      conceptName: "함수",
      schoolLevel: "고등",
      grade: "공통수학",
      domain: "함수",
      description: "입력과 출력의 대응 관계를 식, 그래프, 표로 해석하는 개념",
      prerequisites: ["linear_function", "quadratic_function", "coordinate_plane"],
      nextConcepts: ["exponential_function", "logarithmic_function", "limit_basic"],
      difficultyLevel: 8,
      relatedUnits: ["함수", "지수함수와 로그함수"],
      levelTestQuestionCount: 8,
      testQuestionTypes: ["정의역/치역", "합성함수", "역함수", "그래프 해석"],
      minimumPassScore: 74,
      masteryCriteria: { accuracy: 0.76, maxAverageSeconds: 75, requiredConsecutiveCorrect: 5 },
      commonMistakes: ["대응 관계 혼동", "정의역 제한 누락", "그래프 해석 오류"],
      diagnosisRules: [
        { if: "함수 오답", then: ["linear_function", "quadratic_function", "coordinate_plane"] },
      ],
      recommendedReviewConcepts: ["linear_function", "quadratic_function"],
      levelTestDifficulty: [3, 4, 4, 5],
    },
    {
      id: "exponential_function",
      conceptName: "지수함수",
      schoolLevel: "고등",
      grade: "수학Ⅰ",
      domain: "함수",
      description: "거듭제곱의 지수에 변수가 있는 함수의 성질을 이해하는 개념",
      prerequisites: ["function_basic", "exponent_law", "graph_transformation"],
      nextConcepts: ["logarithmic_function", "limit_basic"],
      difficultyLevel: 8,
      relatedUnits: ["지수함수", "지수함수와 로그함수"],
      levelTestQuestionCount: 7,
      testQuestionTypes: ["지수법칙", "그래프", "방정식", "부등식"],
      minimumPassScore: 74,
      masteryCriteria: { accuracy: 0.76, maxAverageSeconds: 80, requiredConsecutiveCorrect: 4 },
      commonMistakes: ["지수법칙 오류", "밑 조건 누락", "그래프 증가/감소 혼동"],
      diagnosisRules: [
        { if: "지수함수 오답", then: ["function_basic", "exponent_law"] },
      ],
      recommendedReviewConcepts: ["function_basic", "exponent_law"],
      levelTestDifficulty: [3, 4, 4, 5],
    },
    {
      id: "logarithmic_function",
      conceptName: "로그함수",
      schoolLevel: "고등",
      grade: "수학Ⅰ",
      domain: "함수",
      description: "지수의 역연산인 로그를 함수로 해석하는 개념",
      prerequisites: ["exponential_function", "function_basic", "exponent_law"],
      nextConcepts: ["limit_basic", "calculus_basic"],
      difficultyLevel: 8,
      relatedUnits: ["로그함수", "지수함수와 로그함수"],
      levelTestQuestionCount: 7,
      testQuestionTypes: ["로그 정의", "로그법칙", "그래프", "방정식"],
      minimumPassScore: 74,
      masteryCriteria: { accuracy: 0.76, maxAverageSeconds: 85, requiredConsecutiveCorrect: 4 },
      commonMistakes: ["밑 조건 누락", "진수 조건 누락", "로그법칙 오용"],
      diagnosisRules: [
        { if: "로그함수 오답", then: ["exponential_function", "function_basic"] },
      ],
      recommendedReviewConcepts: ["exponential_function", "function_basic"],
      levelTestDifficulty: [3, 4, 4, 5],
    },
    {
      id: "trigonometric_function",
      conceptName: "삼각함수",
      schoolLevel: "고등",
      grade: "수학Ⅰ",
      domain: "함수",
      description: "각의 크기에 따른 삼각비의 변화를 함수로 확장하는 개념",
      prerequisites: ["trigonometric_ratio", "function_basic", "graph_transformation"],
      nextConcepts: ["limit_basic", "calculus_basic", "vector_basic"],
      difficultyLevel: 8,
      relatedUnits: ["삼각함수"],
      levelTestQuestionCount: 8,
      testQuestionTypes: ["호도법", "그래프", "주기", "삼각방정식"],
      minimumPassScore: 74,
      masteryCriteria: { accuracy: 0.76, maxAverageSeconds: 90, requiredConsecutiveCorrect: 5 },
      commonMistakes: ["호도법 변환 오류", "주기/진폭 혼동", "특수각 값 미숙"],
      diagnosisRules: [
        { if: "삼각함수 오답", then: ["trigonometric_ratio", "function_basic"] },
      ],
      recommendedReviewConcepts: ["trigonometric_ratio", "function_basic"],
      levelTestDifficulty: [3, 4, 4, 5],
    },
    {
      id: "sequence_basic",
      conceptName: "수열",
      schoolLevel: "고등",
      grade: "수학Ⅰ",
      domain: "수와 연산",
      description: "규칙을 가진 수의 나열을 일반항과 합으로 표현하는 개념",
      prerequisites: ["algebraic_expression", "function_basic", "pattern_basic"],
      nextConcepts: ["sequence_limit", "calculus_basic"],
      difficultyLevel: 8,
      relatedUnits: ["수열", "수열의 극한"],
      levelTestQuestionCount: 7,
      testQuestionTypes: ["등차수열", "등비수열", "합", "귀납적 정의"],
      minimumPassScore: 74,
      masteryCriteria: { accuracy: 0.76, maxAverageSeconds: 85, requiredConsecutiveCorrect: 4 },
      commonMistakes: ["공차/공비 혼동", "합 공식 오용", "일반항 설정 오류"],
      diagnosisRules: [
        { if: "수열 오답", then: ["algebraic_expression", "pattern_basic"] },
      ],
      recommendedReviewConcepts: ["algebraic_expression", "pattern_basic"],
      levelTestDifficulty: [3, 4, 4, 5],
    },
    {
      id: "limit_basic",
      conceptName: "함수의 극한",
      schoolLevel: "고등",
      grade: "수학Ⅱ",
      domain: "미적분",
      description: "입력값이 특정 값에 가까워질 때 함수값이 가까워지는 값을 해석하는 개념",
      prerequisites: ["function_basic", "rational_expression", "graph_interpretation"],
      nextConcepts: ["differentiation_basic", "integration_basic"],
      difficultyLevel: 9,
      relatedUnits: ["함수의 극한", "수열의 극한"],
      levelTestQuestionCount: 8,
      testQuestionTypes: ["좌극한/우극한", "그래프", "식 변형", "연속"],
      minimumPassScore: 72,
      masteryCriteria: { accuracy: 0.74, maxAverageSeconds: 95, requiredConsecutiveCorrect: 5 },
      commonMistakes: ["함숫값과 극한값 혼동", "좌우극한 누락", "약분 조건 누락"],
      diagnosisRules: [
        { if: "극한 오답", then: ["function_basic", "rational_expression", "graph_interpretation"] },
      ],
      recommendedReviewConcepts: ["function_basic", "rational_expression"],
      levelTestDifficulty: [3, 4, 4, 5],
    },
    {
      id: "differentiation_basic",
      conceptName: "미분",
      schoolLevel: "고등",
      grade: "수학Ⅱ/미적분",
      domain: "미적분",
      description: "함수의 순간 변화율과 접선의 기울기를 구하는 개념",
      prerequisites: ["limit_basic", "function_basic", "polynomial_operation"],
      nextConcepts: ["integration_basic", "optimization", "differentiation_advanced"],
      difficultyLevel: 9,
      relatedUnits: ["미분", "미분법"],
      levelTestQuestionCount: 9,
      testQuestionTypes: ["도함수", "접선", "증가/감소", "극대/극소"],
      minimumPassScore: 72,
      masteryCriteria: { accuracy: 0.74, maxAverageSeconds: 100, requiredConsecutiveCorrect: 5 },
      commonMistakes: ["극한 정의 미이해", "미분계수와 도함수 혼동", "합성함수 미분 오류"],
      diagnosisRules: [
        { if: "미분 오답", then: ["limit_basic", "function_basic", "polynomial_operation"] },
      ],
      recommendedReviewConcepts: ["limit_basic", "function_basic"],
      levelTestDifficulty: [3, 4, 4, 5, 5],
    },
    {
      id: "integration_basic",
      conceptName: "적분",
      schoolLevel: "고등",
      grade: "수학Ⅱ/미적분",
      domain: "미적분",
      description: "변화율을 누적량으로 되돌리거나 곡선 아래 넓이를 구하는 개념",
      prerequisites: ["differentiation_basic", "function_basic", "area_basic"],
      nextConcepts: ["integration_advanced", "probability_distribution"],
      difficultyLevel: 9,
      relatedUnits: ["적분", "적분법"],
      levelTestQuestionCount: 9,
      testQuestionTypes: ["부정적분", "정적분", "넓이", "활용"],
      minimumPassScore: 72,
      masteryCriteria: { accuracy: 0.74, maxAverageSeconds: 105, requiredConsecutiveCorrect: 5 },
      commonMistakes: ["상수 C 누락", "정적분 부호 오류", "넓이와 적분값 혼동"],
      diagnosisRules: [
        { if: "적분 오답", then: ["differentiation_basic", "function_basic", "area_basic"] },
      ],
      recommendedReviewConcepts: ["differentiation_basic", "area_basic"],
      levelTestDifficulty: [3, 4, 4, 5, 5],
    },
    {
      id: "counting_cases",
      conceptName: "경우의 수",
      schoolLevel: "초등/중등/고등",
      grade: "초6~확률과 통계",
      domain: "자료·확률·통계",
      description: "어떤 일이 일어나는 모든 가능한 경우를 빠짐없이 세는 개념",
      prerequisites: ["multiplication_basic", "classification", "pattern_basic"],
      nextConcepts: ["probability_basic", "permutation_combination"],
      difficultyLevel: 6,
      relatedUnits: ["경우의 수", "확률"],
      levelTestQuestionCount: 7,
      testQuestionTypes: ["곱의 법칙", "합의 법칙", "순열", "조합 기초"],
      minimumPassScore: 76,
      masteryCriteria: { accuracy: 0.8, maxAverageSeconds: 70, requiredConsecutiveCorrect: 4 },
      commonMistakes: ["중복/누락", "순서 고려 여부 혼동", "합/곱 법칙 혼동"],
      diagnosisRules: [
        { if: "경우의 수 오답", then: ["multiplication_basic", "classification"] },
      ],
      recommendedReviewConcepts: ["multiplication_basic", "classification"],
      levelTestDifficulty: [2, 3, 4, 4, 5],
    },
    {
      id: "probability_basic",
      conceptName: "확률",
      schoolLevel: "중등/고등",
      grade: "중2~확률과 통계",
      domain: "자료·확률·통계",
      description: "전체 경우 중 특정 사건이 일어날 가능성을 수로 나타내는 개념",
      prerequisites: ["counting_cases", "fraction_basic", "ratio_basic"],
      nextConcepts: ["statistics_basic", "probability_distribution"],
      difficultyLevel: 7,
      relatedUnits: ["확률", "확률과 통계"],
      levelTestQuestionCount: 8,
      testQuestionTypes: ["기본 확률", "여사건", "독립/종속", "조건부확률 기초"],
      minimumPassScore: 75,
      masteryCriteria: { accuracy: 0.78, maxAverageSeconds: 80, requiredConsecutiveCorrect: 5 },
      commonMistakes: ["전체 경우 수 오류", "분자/분모 반대", "중복 계산"],
      diagnosisRules: [
        { if: "확률 오답", then: ["counting_cases", "fraction_basic", "ratio_basic"] },
      ],
      recommendedReviewConcepts: ["counting_cases", "fraction_basic"],
      levelTestDifficulty: [3, 4, 4, 5],
    },
    {
      id: "statistics_basic",
      conceptName: "통계",
      schoolLevel: "중등/고등",
      grade: "중3~확률과 통계",
      domain: "자료·확률·통계",
      description: "자료의 경향과 흩어짐을 수치와 그래프로 해석하는 개념",
      prerequisites: ["average_basic", "data_interpretation", "probability_basic"],
      nextConcepts: ["probability_distribution"],
      difficultyLevel: 7,
      relatedUnits: ["자료의 정리와 해석", "대푯값과 산포도", "통계"],
      levelTestQuestionCount: 8,
      testQuestionTypes: ["평균", "중앙값", "분산", "표준편차", "자료 해석"],
      minimumPassScore: 75,
      masteryCriteria: { accuracy: 0.78, maxAverageSeconds: 80, requiredConsecutiveCorrect: 5 },
      commonMistakes: ["평균/중앙값 혼동", "분산 의미 미이해", "그래프 축 해석 오류"],
      diagnosisRules: [
        { if: "통계 오답", then: ["average_basic", "data_interpretation"] },
      ],
      recommendedReviewConcepts: ["average_basic", "data_interpretation"],
      levelTestDifficulty: [3, 4, 4, 5],
    },
    {
      id: "analytic_geometry",
      conceptName: "도형의 방정식",
      schoolLevel: "고등",
      grade: "공통수학/기하",
      domain: "도형",
      description: "좌표평면에서 직선, 원, 이차곡선을 방정식으로 나타내고 해석하는 개념",
      prerequisites: ["coordinate_plane", "linear_function", "quadratic_function", "pythagorean"],
      nextConcepts: ["conic_section", "vector_basic"],
      difficultyLevel: 8,
      relatedUnits: ["도형의 방정식", "이차곡선"],
      levelTestQuestionCount: 8,
      testQuestionTypes: ["직선 방정식", "원의 방정식", "거리", "이차곡선 기초"],
      minimumPassScore: 74,
      masteryCriteria: { accuracy: 0.76, maxAverageSeconds: 90, requiredConsecutiveCorrect: 5 },
      commonMistakes: ["기울기 해석 오류", "거리공식 오류", "좌표 대입 오류"],
      diagnosisRules: [
        { if: "도형의 방정식 오답", then: ["coordinate_plane", "linear_function", "pythagorean"] },
      ],
      recommendedReviewConcepts: ["coordinate_plane", "linear_function"],
      levelTestDifficulty: [3, 4, 4, 5],
    },
    {
      id: "vector_basic",
      conceptName: "벡터",
      schoolLevel: "고등",
      grade: "기하",
      domain: "도형",
      description: "크기와 방향을 가진 양을 좌표와 연산으로 다루는 개념",
      prerequisites: ["coordinate_plane", "trigonometric_ratio", "analytic_geometry"],
      nextConcepts: ["solid_geometry"],
      difficultyLevel: 9,
      relatedUnits: ["평면벡터", "공간도형과 공간좌표"],
      levelTestQuestionCount: 8,
      testQuestionTypes: ["벡터 연산", "내적", "좌표 표현", "도형 활용"],
      minimumPassScore: 72,
      masteryCriteria: { accuracy: 0.74, maxAverageSeconds: 100, requiredConsecutiveCorrect: 5 },
      commonMistakes: ["방향/크기 혼동", "내적 공식 오류", "좌표 벡터 계산 오류"],
      diagnosisRules: [
        { if: "벡터 오답", then: ["coordinate_plane", "trigonometric_ratio", "analytic_geometry"] },
      ],
      recommendedReviewConcepts: ["coordinate_plane", "trigonometric_ratio"],
      levelTestDifficulty: [3, 4, 4, 5],
    },
  ],
  questionBankPolicy: {
    purpose: "큰 문항은행을 구축하고, 레벨테스트에서는 AI가 대표 문항만 선별해 40~60문항 안에서 정확히 진단한다.",
    targetBankSizeByLevel: {
      "초1": 100,
      "초2": 120,
      "초3": 150,
      "초4": 150,
      "초5": 180,
      "초6": 180,
      "중1": 200,
      "중2": 200,
      "중3": 220,
      "공통수학": 250,
      "수학Ⅰ": 250,
      "수학Ⅱ": 250,
      "미적분": 300,
      "확률과 통계": 200,
      "기하": 200,
    },
    recommendedRepresentativeTestCount: {
      "초1": 8,
      "초2": 10,
      "초3": 12,
      "초4": 12,
      "초5": 15,
      "초6": 15,
      "중1": 18,
      "중2": 18,
      "중3": 20,
      "공통수학": 20,
      "수학Ⅰ": 18,
      "수학Ⅱ": 18,
      "미적분": 20,
      "확률과 통계": 15,
      "기하": 15,
    },
    questionSchema: {
      questionId: "q_m2_linear_function_001",
      conceptId: "linear_function",
      schoolLevel: "중등",
      grade: "중2",
      unit: "일차함수",
      difficulty: 3,
      questionType: "개념확인 | 계산 | 그래프해석 | 문장제 | 추론 | 응용",
      answer: "정답",
      explanation: "풀이 설명",
      prerequisiteConcepts: ["coordinate_plane", "linear_equation", "proportion"],
      nextConcepts: ["quadratic_function"],
      estimatedSolveTime: 45,
      commonMistakes: ["기울기와 절편 혼동", "좌표 대입 오류"],
      diagnosisRule: {
        ifWrong: ["coordinate_plane", "linear_equation"],
        ifSlow: ["linear_function"],
        ifUnknown: ["linear_function", "coordinate_plane"],
      },
    },
  },
  diagnosisChains: [
    {
      blockedConcept: "quadratic_equation",
      readablePath: ["이차방정식", "인수분해", "다항식 곱셈", "문자식 계산", "정수와 유리수 계산"],
      trace: ["factorization", "polynomial_operation", "algebraic_expression", "integer_rational"],
      recommendation: "이차방정식 풀이 전 인수분해와 다항식 전개를 먼저 복습합니다.",
    },
    {
      blockedConcept: "proportion",
      readablePath: ["비례식", "비율", "분수 계산", "나눗셈"],
      trace: ["ratio_basic", "fraction_operations", "division_basic"],
      recommendation: "비례식 문제 전 비율과 분수 계산을 먼저 복습합니다.",
    },
    {
      blockedConcept: "trigonometric_ratio",
      readablePath: ["삼각비", "직각삼각형", "피타고라스 정리", "비율"],
      trace: ["pythagorean", "triangle_basic", "ratio_basic"],
      recommendation: "삼각비 진도 전 직각삼각형, 피타고라스, 비율을 점검합니다.",
    },
    {
      blockedConcept: "linear_equation",
      readablePath: ["일차방정식", "문자식", "정수와 유리수", "등식의 성질"],
      trace: ["algebraic_expression", "integer_rational", "equation_property"],
      recommendation: "일차방정식 전 문자식 계산과 부호 계산을 먼저 안정화합니다.",
    },
    {
      blockedConcept: "quadratic_function",
      readablePath: ["이차함수", "좌표평면", "일차함수", "이차방정식"],
      trace: ["coordinate_plane", "linear_function", "quadratic_equation"],
      recommendation: "이차함수 전 좌표평면, 일차함수, 이차방정식을 복습합니다.",
    },
  ],
  levelTestDesign: {
    entryPolicy: "학년은 출제 범위의 상한으로만 사용하고, 실제 시작점은 선수개념 진단 결과로 결정한다.",
    adaptivePolicy: {
      enabled: true,
      targetQuestionCountRange: [40, 60],
      maxQuestionCount: 70,
      initialProbe: {
        defaultStartLevel: "초4",
        questionCount: 10,
        selection: "수와 연산, 도형, 자료 해석에서 대표 개념을 골고루 출제한다.",
      },
      jumpRules: [
        { ifAccuracyGte: 0.8, from: "초4", to: "초6", reason: "초중학년 기초 안정" },
        { ifAccuracyGte: 0.8, from: "초6", to: "중2", reason: "초등 고학년 핵심 안정" },
        { ifAccuracyGte: 0.8, from: "중2", to: "공통수학", reason: "중등 핵심 개념 안정" },
        { ifAccuracyLt: 0.6, action: "prerequisite_backtrack", reason: "선수개념 결손 가능성" },
        { ifSlowRateGte: 0.35, action: "same_level_recheck", reason: "정답이어도 자동화 부족" },
      ],
      backtrackRules: [
        { failedConcept: "linear_equation", inspect: ["algebraic_expression", "integer_rational", "equation_property"] },
        { failedConcept: "proportion", inspect: ["ratio_basic", "fraction_operations", "division_basic"] },
        { failedConcept: "quadratic_function", inspect: ["coordinate_plane", "linear_function", "quadratic_equation"] },
        { failedConcept: "trigonometric_ratio", inspect: ["pythagorean", "ratio_basic", "triangle_basic"] },
      ],
      stopConditions: [
        "목표 문항 수 40~60문항 안에서 영역별 신뢰도가 충분할 때",
        "현재 학습 시작 개념이 2회 이상 같은 후보로 수렴할 때",
        "학생이 모름을 연속 선택하여 더 높은 개념 출제가 의미 없을 때",
        "최대 70문항에 도달했을 때",
      ],
    },
    abilityDimensions: [
      { id: "calculation", label: "계산 능력", relatedConcepts: ["addition_basic", "subtraction_basic", "multiplication_basic", "division_basic", "fraction_operations", "integer_rational"] },
      { id: "number_sense", label: "수 감각", relatedConcepts: ["number_sense", "place_value", "integer_rational"] },
      { id: "fraction", label: "분수", relatedConcepts: ["fraction_basic", "fraction_operations"] },
      { id: "decimal", label: "소수", relatedConcepts: ["decimal_basic"] },
      { id: "ratio", label: "비율", relatedConcepts: ["ratio_basic", "proportion"] },
      { id: "algebra", label: "문자식", relatedConcepts: ["algebraic_expression", "polynomial_operation", "factorization"] },
      { id: "equation", label: "방정식", relatedConcepts: ["linear_equation", "simultaneous_equation", "quadratic_equation"] },
      { id: "function", label: "함수", relatedConcepts: ["linear_function", "quadratic_function", "function_basic", "exponential_function", "logarithmic_function", "trigonometric_function"] },
      { id: "geometry", label: "도형", relatedConcepts: ["triangle_basic", "similarity", "pythagorean", "analytic_geometry", "vector_basic"] },
      { id: "trigonometry", label: "삼각비", relatedConcepts: ["trigonometric_ratio", "trigonometric_function"] },
      { id: "probability", label: "확률", relatedConcepts: ["counting_cases", "probability_basic"] },
      { id: "statistics", label: "통계", relatedConcepts: ["statistics_basic", "probability_distribution"] },
      { id: "logical_thinking", label: "논리적 사고력", relatedConcepts: ["proof_basic", "set_logic", "function_basic"] },
      { id: "application", label: "응용 문제 해결 능력", relatedConcepts: ["proportion", "linear_equation", "quadratic_function", "calculus_basic"] },
    ],
    scoring: {
      correct: 1,
      slowButCorrect: 0.7,
      unknown: 0,
      wrong: 0,
      timePenaltyOnly: true,
    },
    placementRules: [
      "선수개념 masteryCriteria를 통과하지 못하면 현재 학년 단원보다 복습 개념을 우선 추천한다.",
      "오답은 해당 문항 concept의 diagnosisRules를 따라 원인 후보 개념으로 역추적한다.",
      "시간초과 후 정답을 맞히면 오답이 아니라 slowButCorrect로 처리한다.",
      "모름 선택은 unknown으로 처리하고 해당 concept을 recommendedStartConcept 후보로 올린다.",
    ],
    resultSchema: {
      studentLevel: "중1",
      recommendedStartConcept: "fraction_operations",
      weakConcepts: ["분수 계산", "비율", "문자식"],
      readyConcepts: ["자연수 계산", "기본 도형"],
      blockedConcepts: ["일차방정식", "일차함수"],
      recommendation: "중1 진도 시작 전 초등 5~6학년의 분수·비율 단원을 먼저 복습해야 합니다.",
    },
    visualizationBuckets: {
      strongConcepts: [],
      weakConcepts: [],
      blockedConcepts: [],
      currentStudyConcepts: [],
      reviewRecommendedConcepts: [],
      nextProgressConcepts: [],
    },
  },
};

mathConceptRoadmap.graph = {
  nodes: mathConceptRoadmap.concepts.map((concept) => ({
    id: concept.id,
    label: concept.conceptName,
    grade: concept.grade,
    domain: concept.domain,
    schoolLevel: concept.schoolLevel,
    difficultyLevel: concept.difficultyLevel,
  })),
  edges: mathConceptRoadmap.concepts.flatMap((concept) =>
    concept.nextConcepts.map((nextId) => ({
      from: concept.id,
      to: nextId,
      relation: "선수학습",
    })),
  ),
};

mathConceptRoadmap.sampleDiagnosisResult = {
  studentLevel: "중1",
  recommendedStartConcept: "fraction_operations",
  weakConcepts: ["분수 계산", "비율", "문자식"],
  readyConcepts: ["자연수 계산", "기본 도형"],
  blockedConcepts: ["일차방정식", "일차함수"],
  recommendation: "중1 진도 시작 전 초등 5~6학년의 분수·비율 단원을 먼저 복습해야 합니다.",
  visualization: {
    strongConcepts: ["number_sense", "addition_basic", "subtraction_basic", "multiplication_basic"],
    weakConcepts: ["fraction_operations", "ratio_basic", "algebraic_expression"],
    blockedConcepts: ["linear_equation", "linear_function"],
    currentStudyConcepts: ["fraction_operations"],
    reviewRecommendedConcepts: ["fraction_basic", "factor_multiple", "division_basic"],
    nextProgressConcepts: ["ratio_basic", "proportion", "integer_rational"],
  },
};

if (typeof module !== "undefined") {
  module.exports = mathConceptRoadmap;
}
